#Requires -Version 5.1
#Requires -RunAsAdministrator

<#
.SYNOPSIS
    Corex Task Scheduler Setup - Windows Task Scheduler Configuration

.DESCRIPTION
    This PowerShell script configures Windows Task Scheduler to replace the Linux scheduler
    for running Laravel commands and background tasks (cron jobs equivalent).

.PARAMETER Action
    The action to perform: Install, Uninstall, Enable, Disable, List, Test

.EXAMPLE
    PS> .\SetupTaskScheduler.ps1 -Action Install
    PS> .\SetupTaskScheduler.ps1 -Action Test
    PS> .\SetupTaskScheduler.ps1 -Action List
#>

param(
    [Parameter(Mandatory=$false)]
    [ValidateSet('Install', 'Uninstall', 'Enable', 'Disable', 'List', 'Test')]
    [string]$Action = 'Install'
)

# ============================================================================
# Configuration
# ============================================================================
$ErrorActionPreference = 'Stop'
$VerbosePreference = 'Continue'

$ProjectRoot = Split-Path -Parent $PSScriptRoot
$BackendPath = Join-Path $ProjectRoot 'backend'
$ArtisanPath = Join-Path $BackendPath 'artisan'
$PhpPath = 'php.exe'  # Assumes PHP is in PATH
$LogDir = Join-Path $ProjectRoot 'logs'
$TaskLogFile = Join-Path $LogDir 'task-scheduler.log'
$TasksFolder = '\Corex'  # Task Scheduler folder

# Task definitions for Laravel scheduler and background tasks
$Tasks = @(
    @{
        Name        = 'Corex-Laravel-Scheduler'
        Description = 'Runs Laravel scheduler every minute'
        Script      = @"
`$projectRoot = '$ProjectRoot'
`$backendPath = Join-Path `$projectRoot 'backend'
Push-Location `$backendPath
& php artisan schedule:run
Pop-Location
"@
        Interval    = 1  # Every minute
        Repeat      = 60  # For 1 hour (can be extended)
    }
    @{
        Name        = 'Corex-Queue-Worker'
        Description = 'Processes Laravel queue jobs'
        Script      = @"
`$projectRoot = '$ProjectRoot'
`$backendPath = Join-Path `$projectRoot 'backend'
Push-Location `$backendPath
& php artisan queue:work redis --max-jobs=1000 --max-time=3600 --sleep=3
Pop-Location
"@
        StartTime   = '00:00:00'
        Frequency   = 'Once'  # Runs continuously, restarts hourly
        Trigger     = 'OnLogon'  # Or you can use 'Daily' with StartTime
    }
    @{
        Name        = 'Corex-Cache-Clear'
        Description = 'Clears application cache daily'
        Script      = @"
`$projectRoot = '$ProjectRoot'
`$backendPath = Join-Path `$projectRoot 'backend'
Push-Location `$backendPath
& php artisan cache:clear
Pop-Location
"@
        StartTime   = '02:00:00'
        Frequency   = 'Daily'
    }
    @{
        Name        = 'Corex-Backup-Database'
        Description = 'Creates daily database backup'
        Script      = @"
`$projectRoot = '$ProjectRoot'
`$backendPath = Join-Path `$projectRoot 'backend'
Push-Location `$backendPath
& php artisan backup:run
Pop-Location
"@
        StartTime   = '03:00:00'
        Frequency   = 'Daily'
    }
)

# ============================================================================
# Helper Functions
# ============================================================================

function Write-Log {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$Message,
        
        [Parameter(Mandatory=$false)]
        [ValidateSet('Info', 'Warning', 'Error', 'Success')]
        [string]$Level = 'Info',
        
        [Parameter(Mandatory=$false)]
        [switch]$ToFile
    )
    
    $timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    $logMessage = "[$timestamp] [$Level] $Message"
    
    switch ($Level) {
        'Error'   { Write-Host $logMessage -ForegroundColor Red }
        'Warning' { Write-Host $logMessage -ForegroundColor Yellow }
        'Success' { Write-Host $logMessage -ForegroundColor Green }
        default   { Write-Host $logMessage -ForegroundColor Cyan }
    }
    
    if ($ToFile) {
        if (-not (Test-Path $LogDir)) {
            New-Item -ItemType Directory -Path $LogDir -Force | Out-Null
        }
        Add-Content -Path $TaskLogFile -Value $logMessage
    }
}

function Test-PhpAvailable {
    try {
        $null = & $PhpPath --version
        return $true
    } catch {
        Write-Log "PHP is not installed or not in PATH" -Level Error
        return $false
    }
}

function Test-LaravelProject {
    if (-not (Test-Path $ArtisanPath)) {
        Write-Log "Laravel artisan file not found at $ArtisanPath" -Level Error
        return $false
    }
    return $true
}

function Create-PSTaskAction {
    param(
        [string]$Script,
        [string]$TaskName
    )
    
    $scriptPath = Join-Path $LogDir "task-$($TaskName -replace ' ', '_').ps1"
    
    # Create wrapper script
    $wrapper = @"
# Task: $TaskName
# Auto-generated by SetupTaskScheduler.ps1

`$LogDir = '$LogDir'
`$LogFile = Join-Path `$LogDir 'task-$(($TaskName -replace ' ', '_')).log'

function Write-TaskLog {
    param([string]`$Message)
    `$ts = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    "`$ts | `$Message" | Add-Content -Path `$LogFile
}

try {
    Write-TaskLog 'Task started'
    $Script
    Write-TaskLog 'Task completed successfully'
} catch {
    Write-TaskLog "Task failed: `$_"
    exit 1
}
"@
    
    Set-Content -Path $scriptPath -Value $wrapper -Force
    
    return @{
        Program = 'powershell.exe'
        Arguments = "-ExecutionPolicy Bypass -NoProfile -File `"$scriptPath`""
    }
}

function Register-ScheduledTask_Custom {
    param(
        [string]$TaskName,
        [string]$TaskDescription,
        [hashtable]$Action,
        [ValidateSet('Once', 'Daily', 'Weekly', 'Hourly', 'OnLogon')]
        [string]$Trigger = 'Daily',
        [string]$StartTime = '01:00:00'
    )
    
    try {
        $taskPath = "$TasksFolder\$TaskName"
        
        # Check if task already exists
        $existingTask = Get-ScheduledTask -TaskPath $TasksFolder -TaskName $TaskName -ErrorAction SilentlyContinue
        if ($existingTask) {
            Write-Log "Task $TaskName already exists, updating..." -ToFile
            Unregister-ScheduledTask -TaskPath $TasksFolder -TaskName $TaskName -Confirm:$false
        }
        
        # Create trigger
        switch ($Trigger) {
            'Daily' {
                $at = [datetime]$StartTime
                $CimTrigger = New-ScheduledTaskTrigger -Daily -At $at
            }
            'Hourly' {
                $CimTrigger = New-ScheduledTaskTrigger -Once -At (Get-Date) -RepetitionInterval (New-TimeSpan -Minutes 60) -RepetitionDuration (New-TimeSpan -Hours 23)
            }
            'OnLogon' {
                $CimTrigger = New-ScheduledTaskTrigger -AtLogon
            }
            default {
                $CimTrigger = New-ScheduledTaskTrigger -Once -At (Get-Date)
            }
        }
        
        # Create action
        $CimAction = New-ScheduledTaskAction -Execute $Action.Program -Argument $Action.Arguments -WorkingDirectory $ProjectRoot
        
        # Create settings
        $CimSettings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -RunOnlyIfNetworkAvailable -Compatibility Win8
        
        # Create principal (run as SYSTEM)
        $CimPrincipal = New-ScheduledTaskPrincipal -UserID "SYSTEM" -LogonType ServiceAccount -RunLevel Highest
        
        # Register task
        Register-ScheduledTask -TaskName $TaskName `
            -TaskPath $TasksFolder `
            -Action $CimAction `
            -Trigger $CimTrigger `
            -Settings $CimSettings `
            -Principal $CimPrincipal `
            -Description $TaskDescription `
            -Force | Out-Null
        
        Write-Log "Task registered: $TaskName" -Level Success -ToFile
        return $true
    } catch {
        Write-Log "Error registering task $TaskName : $_" -Level Error -ToFile
        return $false
    }
}

# ============================================================================
# Task Management Functions
# ============================================================================

function Install-Tasks {
    Write-Log "Installing Corex Task Scheduler tasks..." -ToFile
    
    if (-not (Test-PhpAvailable)) { exit 1 }
    if (-not (Test-LaravelProject)) { exit 1 }
    
    # Create task folder
    try {
        $folder = Get-ScheduledTask -TaskPath $TasksFolder -ErrorAction SilentlyContinue
        if (-not $folder) {
            Write-Log "Creating task scheduler folder: $TasksFolder" -ToFile
            $null = New-Item -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tree$TasksFolder" -Force
        }
    } catch {}
    
    $installCount = 0
    
    foreach ($task in $Tasks) {
        Write-Log "Installing task: $($task.Name)" -ToFile
        
        $action = Create-PSTaskAction -Script $task.Script -TaskName $task.Name
        $trigger = if ($task.ContainsKey('Interval')) { 'Hourly' } else { $task.Frequency }
        $startTime = if ($task.ContainsKey('StartTime')) { $task.StartTime } else { '01:00:00' }
        
        if (Register-ScheduledTask_Custom -TaskName $task.Name `
                -TaskDescription $task.Description `
                -Action $action `
                -Trigger $trigger `
                -StartTime $startTime) {
            $installCount++
        }
    }
    
    Write-Log "Installed $installCount/$($Tasks.Count) tasks successfully" -Level Success -ToFile
}

function Uninstall-Tasks {
    Write-Log "Uninstalling Corex Task Scheduler tasks..." -ToFile
    
    try {
        $taskFolder = Get-ScheduledTask -TaskPath $TasksFolder -ErrorAction SilentlyContinue
        if ($taskFolder) {
            foreach ($task in $Tasks) {
                $scheduledTask = Get-ScheduledTask -TaskPath $TasksFolder -TaskName $task.Name -ErrorAction SilentlyContinue
                if ($scheduledTask) {
                    Unregister-ScheduledTask -TaskPath $TasksFolder -TaskName $task.Name -Confirm:$false
                    Write-Log "Uninstalled task: $($task.Name)" -Level Success -ToFile
                }
            }
        }
    } catch {
        Write-Log "Error uninstalling tasks: $_" -Level Error -ToFile
        exit 1
    }
}

function Enable-Tasks {
    Write-Log "Enabling Corex tasks..." -ToFile
    
    foreach ($task in $Tasks) {
        try {
            $scheduledTask = Get-ScheduledTask -TaskPath $TasksFolder -TaskName $task.Name -ErrorAction SilentlyContinue
            if ($scheduledTask -and $scheduledTask.State -eq 'Disabled') {
                Enable-ScheduledTask -TaskPath $TasksFolder -TaskName $task.Name
                Write-Log "Enabled task: $($task.Name)" -Level Success -ToFile
            }
        } catch {
            Write-Log "Error enabling $($task.Name): $_" -Level Warning -ToFile
        }
    }
}

function Disable-Tasks {
    Write-Log "Disabling Corex tasks..." -ToFile
    
    foreach ($task in $Tasks) {
        try {
            $scheduledTask = Get-ScheduledTask -TaskPath $TasksFolder -TaskName $task.Name -ErrorAction SilentlyContinue
            if ($scheduledTask -and $scheduledTask.State -eq 'Ready') {
                Disable-ScheduledTask -TaskPath $TasksFolder -TaskName $task.Name
                Write-Log "Disabled task: $($task.Name)" -Level Success -ToFile
            }
        } catch {
            Write-Log "Error disabling $($task.Name): $_" -Level Warning -ToFile
        }
    }
}

function List-Tasks {
    Write-Log "Corex scheduled tasks:" -ToFile
    
    try {
        $scheduledTasks = Get-ScheduledTask -TaskPath $TasksFolder -ErrorAction SilentlyContinue
        
        if ($scheduledTasks) {
            foreach ($task in $scheduledTasks) {
                $status = $task.State
                $lastRun = $task.LastRunTime
                $nextRun = $task.NextRunTime
                
                Write-Host ""
                Write-Host "Task: $($task.TaskName)" -ForegroundColor Cyan
                Write-Host "  Status: $status"
                Write-Host "  Last run: $lastRun"
                Write-Host "  Next run: $nextRun"
            }
        } else {
            Write-Log "No Corex tasks found" -Level Warning -ToFile
        }
    } catch {
        Write-Log "Error listing tasks: $_" -Level Error -ToFile
    }
}

function Test-Tasks {
    Write-Log "Testing Corex tasks..." -ToFile
    
    Write-Log "Testing Laravel scheduler..." -ToFile
    try {
        Push-Location $BackendPath
        & $PhpPath artisan schedule:list
        Pop-Location
    } catch {
        Write-Log "Error testing Laravel scheduler: $_" -Level Error -ToFile
    }
}

# ============================================================================
# Main Execution
# ============================================================================

try {
    switch ($Action) {
        'Install' {
            Install-Tasks
        }
        'Uninstall' {
            Uninstall-Tasks
        }
        'Enable' {
            Enable-Tasks
        }
        'Disable' {
            Disable-Tasks
        }
        'List' {
            List-Tasks
        }
        'Test' {
            Test-Tasks
        }
        default {
            Write-Log "Unknown action: $Action" -Level Error
            exit 1
        }
    }
} catch {
    Write-Log "Fatal error: $_" -Level Error -ToFile
    exit 1
}
