#Requires -Version 5.1

param(
    [string]$InstallDir = "$env:ProgramFiles\Corex",
    [string]$DataDir = "$env:LOCALAPPDATA\Corex",
    [string]$LogDir = "$DataDir\logs",
    [int]$Port = 6379
)

$ErrorActionPreference = 'Stop'
$LogDir = New-Item -ItemType Directory -Path $LogDir -Force | Select-Object -ExpandProperty FullName
$LogFile = "$LogDir\setup-redis-windows.log"
$ConfDir = New-Item -ItemType Directory -Path "$InstallDir\conf" -Force | Select-Object -ExpandProperty FullName
$RedisDir = "$InstallDir\tools\redis"

function Log { param([string]$M) Write-Host "$M" -ForegroundColor Gray; "$M" | Out-File $LogFile -Encoding utf8 -Append }
function Ok { param([string]$M) Write-Host "✓ $M" -ForegroundColor Green }

Log "=== Redis Configuration for Windows ==="

$redisConf = @"
# Corex Redis Configuration for Windows
# Generated by setup-redis-windows.ps1

# Bind to localhost only
bind 127.0.0.1 ::1
protected-mode yes
port $Port
tcp-backlog 511
timeout 0
tcp-keepalive 300

# Windows-specific: use a log file instead of syslog
daemonize no
supervised no
loglevel notice
logfile "$DataDir\logs\redis.log"

# Databases
databases 16
always-show-logo no

# Snapshots (RDB)
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir $DataDir\database

# Master replication (disabled for desktop)
replica-serve-stale-data yes
replica-read-only yes
repl-diskless-sync no
repl-diskless-sync-delay 5
repl-disable-tcp-nodelay no
replica-priority 100

# Security
rename-command FLUSHALL ""
rename-command FLUSHDB ""
rename-command CONFIG ""
rename-command KEYS ""
requirepass ""
rename-command SHUTDOWN "SHUTDOWN_COREX"

# Memory management
maxmemory 512mb
maxmemory-policy allkeys-lru
maxmemory-samples 5

# Lazy freeing
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes
replica-lazy-flush yes
lazyfree-lazy-user-del yes

# Append-only file (AOF)
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec
no-appendfsync-on-rewrite yes
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
aof-load-truncated yes
aof-use-rdb-preamble yes

# Slow log
slowlog-log-slower-than 10000
slowlog-max-len 128

# Latency monitor
latency-monitor-threshold 100

# Event notification (disabled for desktop)
notify-keyspace-events ""

# Advanced
hash-max-ziplist-entries 512
hash-max-ziplist-value 64
list-max-ziplist-size -2
zset-max-ziplist-entries 128
zset-max-ziplist-value 64
set-max-intset-entries 512
zset-max-listpack-entries 128
zset-max-listpack-value 64
hash-max-listpack-entries 512
hash-max-listpack-value 64
list-compress-depth 0
stream-node-max-bytes 4096
stream-node-max-entries 100
activerehashing yes
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit replica 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60
hz 10
dynamic-hz yes
aof-rewrite-incremental-fsync yes
rdb-save-incremental-fsync yes
jemalloc-bg-thread yes
"@

$redisConfPath = "$ConfDir\redis.conf"
$redisConf | Out-File $redisConfPath -Encoding ascii -NoNewline
Ok "Redis configuration written: $redisConfPath"

# Create Redis data directory
New-Item -ItemType Directory -Path "$DataDir\database" -Force -ErrorAction SilentlyContinue | Out-Null
Log "Redis data directory: $DataDir\database"

# Create a test connection script
$testScript = "$LogDir\test-redis-connection.ps1"
@"
try {
    `$redis = [System.Net.Sockets.TcpClient]::new('127.0.0.1', $Port)
    `$stream = `$redis.GetStream()
    `$writer = new-object System.IO.StreamWriter(`$stream)
    `$writer.WriteLine('PING')
    `$writer.Flush()
    `$reader = new-object System.IO.StreamReader(`$stream)
    `$response = `$reader.ReadLine()
    if (`$response -match 'PONG') {
        Write-Host "✓ Redis connection OK" -ForegroundColor Green
    } else {
        Write-Host "✗ Unexpected response: `$response" -ForegroundColor Red
    }
    `$redis.Close()
} catch {
    Write-Host "✗ Redis connection failed: `$_" -ForegroundColor Red
}
"@ | Out-File $testScript -Encoding ascii

Log "Test script: $testScript"
Log "Log: $LogFile"
