#!/usr/bin/env bash
# ===========================================================================
#  Corex.dev — Complete Development Environment Setup
# ===========================================================================
#  Usage:
#    ./scripts/init-dev.sh           Full environment setup (run once)
#    source ./scripts/init-dev.sh    Load helper functions into shell
#    ./scripts/init-dev.sh --quick   Skip build/seeds, just start services
#    ./scripts/init-dev.sh --reset   Destroy volumes and start fresh
#    ./scripts/init-dev.sh --ci      Non-interactive, no sudo, no BrowserSync
#
#  Helper functions (available after sourcing):
#    start-dev    Start all services
#    stop-dev     Stop all services
#    logs         Tail combined service logs
#    test         Run all test suites
#    clean        Remove volumes, caches, and build artifacts
# ===========================================================================

set -euo pipefail

# ── Configuration ──────────────────────────────────────────────────────────
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_DIR="$PROJECT_DIR/backend"
AI_GATEWAY_DIR="$PROJECT_DIR/ai-gateway"
FRONTEND_DIR="$PROJECT_DIR/frontend"
MONITORING_DIR="$PROJECT_DIR/infra/monitoring"

COMPOSE_FILE="$PROJECT_DIR/docker-compose.yml"
MONITORING_COMPOSE="$MONITORING_DIR/docker-compose.monitoring.yml"
ENV_FILE="$BACKEND_DIR/.env"
ENV_EXAMPLE="$BACKEND_DIR/.env.example"

DOCKER_COMPOSE="docker compose"
DOCKER_COMPOSE_MONITORING="docker compose -f $MONITORING_COMPOSE -p corex-monitoring"

# Color output
RESET='\033[0m'
BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'

log_info()  { echo -e "${GREEN}[INFO]${RESET}  $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
log_error() { echo -e "${RED}[ERROR]${RESET} $*"; }
log_step()  { echo -e "\n${BOLD}${CYAN}══ $* ══${RESET}\n"; }
log_banner() {
    echo -e "${CYAN}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    printf "║  %-60s  ║\n" "$*"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${RESET}"
}

# ═══════════════════════════════════════════════════════════════════════════
#  STEP 1 — Docker & Docker Compose Check
# ═══════════════════════════════════════════════════════════════════════════

check_docker() {
    log_step "1/15 — Checking Docker installation"

    if ! command -v docker &>/dev/null; then
        log_error "Docker is not installed."
        echo "  Install Docker: https://docs.docker.com/engine/install/"
        echo "  Or use the quick-install script:"
        echo "    curl -fsSL https://get.docker.com | sh"
        exit 1
    fi

    DOCKER_VERSION=$(docker --version 2>/dev/null | grep -oP '\d+\.\d+\.\d+' | head -1 || true)
    log_info "Docker: $DOCKER_VERSION"

    if ! docker info &>/dev/null; then
        log_error "Docker daemon is not running or current user lacks permissions."
        echo "  Try: sudo usermod -aG docker $USER && newgrp docker"
        exit 1
    fi

    log_info "Docker daemon is running"
}

check_docker_compose() {
    log_step "2/15 — Checking Docker Compose"

    if docker compose version &>/dev/null; then
        COMPOSE_VERSION=$(docker compose version 2>/dev/null | grep -oP '\d+\.\d+\.\d+' | head -1 || true)
        log_info "Docker Compose (plugin): $COMPOSE_VERSION"
    elif docker-compose --version &>/dev/null; then
        DOCKER_COMPOSE="docker-compose"
        DOCKER_COMPOSE_MONITORING="docker-compose -f $MONITORING_COMPOSE -p corex-monitoring"
        log_warn "Using docker-compose (deprecated, upgrade to plugin)"
    else
        log_error "Docker Compose is not installed."
        echo "  Install: sudo apt-get install docker-compose-plugin"
        echo "  Or:      https://docs.docker.com/compose/install/"
        exit 1
    fi
}

# ═══════════════════════════════════════════════════════════════════════════
#  STEP 3 — Environment File
# ═══════════════════════════════════════════════════════════════════════════

create_env_file() {
    log_step "3/15 — Creating environment file"

    if [[ -f "$ENV_FILE" ]]; then
        log_warn ".env already exists at $ENV_FILE (backing up to .env.backup)"
        cp "$ENV_FILE" "$ENV_FILE.backup"
    fi

    local JWT_SECRET
    JWT_SECRET=$(openssl rand -base64 64 | tr -d '\n' || head -c 64 /dev/urandom | base64 -w0)
    local REDIS_PASSWORD
    REDIS_PASSWORD=$(openssl rand -base64 24 | tr -d '\n' || head -c 24 /dev/urandom | base64 -w0)
    local DB_PASSWORD
    DB_PASSWORD=$(openssl rand -base64 16 | tr -d '\n' || head -c 16 /dev/urandom | base64 -w0)

    cat > "$ENV_FILE" <<EOF
# ═══════════════════════════════════════════════════════════════════════════
#  Corex.dev — Development Environment (auto-generated by init-dev.sh)
# ═══════════════════════════════════════════════════════════════════════════

APP_NAME=Corex
APP_ENV=local
APP_KEY=
APP_URL=http://localhost:8080
APP_DEBUG=true
APP_ADMIN_EMAIL=admin@corex.dev

DB_CONNECTION=pgsql
DB_HOST=localhost
DB_PORT=5432
DB_DATABASE=corex
DB_USERNAME=corex
DB_PASSWORD=${DB_PASSWORD}

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_CONNECTION=sync
BROADCAST_DRIVER=log

REDIS_HOST=localhost
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=log
MAIL_FROM_ADDRESS=noreply@corex.dev
MAIL_FROM_NAME=Corex

JWT_SECRET=${JWT_SECRET}
JWT_ALGORITHM=HS256
JWT_PUBLIC_KEY=""
JWT_PRIVATE_KEY=""
JWT_TTL=10080
JWT_REFRESH_TTL=20160

AI_GATEWAY_URL=http://localhost:8000
AI_GATEWAY_API_KEY=dev-key

SANCTUM_STATEFUL_DOMAINS=localhost,localhost:3000,localhost:8000,localhost:8080
SANCTUM_TOKEN_PREFIX=corex_

LOG_CHANNEL=stack
LOG_LEVEL=debug

FRONTEND_URL=http://localhost:5173
CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:8080,http://localhost:8000

SESSION_DRIVER=file
SCOUT_DRIVER=collection

OPENAI_API_KEY=
ANTHROPIC_API_KEY=
GROQ_API_KEY=
DEEPSEEK_API_KEY=

SENTRY_LARAVEL_DSN=
SENTRY_DSN=
SENTRY_SAMPLE_RATE=0.0

HEALTH_CHECK_REDIS_ENABLED=false
HEALTH_CHECK_DATABASE_ENABLED=false
HEALTH_CHECK_STORAGE_ENABLED=false

GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=admin
PROMETHEUS_PASSWORD=dev
SLACK_WEBHOOK=
PAGERDUTY_ROUTING_KEY=
EOF

    log_info "Created $ENV_FILE"
}

# ═══════════════════════════════════════════════════════════════════════════
#  STEP 4 — Self-Signed SSL Certificates
# ═══════════════════════════════════════════════════════════════════════════

generate_ssl_certs() {
    log_step "4/15 — Generating self-signed SSL certificates"

    local SSL_DIR="$PROJECT_DIR/docker/nginx/ssl"
    mkdir -p "$SSL_DIR"

    if [[ -f "$SSL_DIR/fullchain.pem" && -f "$SSL_DIR/privkey.pem" ]]; then
        log_info "SSL certificates already exist at $SSL_DIR"
        return
    fi

    # Generate CA key and cert
    openssl req -x509 -nodes -new -sha256 \
        -days 3650 \
        -newkey rsa:2048 \
        -keyout "$SSL_DIR/ca-key.pem" \
        -out "$SSL_DIR/ca.pem" \
        -subj "/C=US/ST=California/L=San Francisco/O=Corex Dev/CN=Corex Dev CA" \
        2>/dev/null

    # Generate wildcard cert for *.corex.dev using the CA
    cat > "$SSL_DIR/domains.ext" <<EOF
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage=digitalSignature,keyEncipherment
extendedKeyUsage=serverAuth,clientAuth
subjectAltName=@alt_names

[alt_names]
DNS.1=corex.dev
DNS.2=*.corex.dev
DNS.3=localhost
DNS.4=*.localhost
DNS.5=api.corex.dev
DNS.6=console.corex.dev
EOF

    openssl req -new -nodes -newkey rsa:2048 \
        -keyout "$SSL_DIR/privkey.pem" \
        -out "$SSL_DIR/csr.pem" \
        -subj "/C=US/ST=California/L=San Francisco/O=Corex Dev/CN=corex.dev" \
        2>/dev/null

    openssl x509 -req -sha256 -days 3650 \
        -in "$SSL_DIR/csr.pem" \
        -CA "$SSL_DIR/ca.pem" \
        -CAkey "$SSL_DIR/ca-key.pem" \
        -CAcreateserial \
        -out "$SSL_DIR/fullchain.pem" \
        -extfile "$SSL_DIR/domains.ext" \
        2>/dev/null

    # Copy for nginx
    cp "$SSL_DIR/fullchain.pem" "$SSL_DIR/cert.pem"
    chmod 644 "$SSL_DIR/"*.pem
    chmod 600 "$SSL_DIR/privkey.pem"
    rm -f "$SSL_DIR/domains.ext" "$SSL_DIR/csr.pem" "$SSL_DIR/ca-key.pem" "$SSL_DIR/ca.pem" "$SSL_DIR/ca.srl"

    log_info "Self-signed certificates created at $SSL_DIR"
    log_warn "Add CA to your trust store to avoid browser warnings:"
    echo "  sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain $SSL_DIR/ca.pem (macOS)"
    echo "  sudo cp $SSL_DIR/ca.pem /usr/local/share/ca-certificates/corex-ca.crt && sudo update-ca-certificates (Linux)"
}

# ═══════════════════════════════════════════════════════════════════════════
#  STEP 5 — Laravel Key Generation
# ═══════════════════════════════════════════════════════════════════════════

generate_laravel_key() {
    log_step "5/15 — Generating Laravel application key"

    cd "$BACKEND_DIR"

    if ! grep -q "^APP_KEY=base64:" ".env" 2>/dev/null; then
        php artisan key:generate --force --no-interaction 2>/dev/null || {
            log_warn "PHP not available locally — generating APP_KEY manually"
            local key
            key=$(openssl rand -base64 32)
            sed -i "s|^APP_KEY=.*|APP_KEY=base64:${key}|" "$ENV_FILE"
        }
        log_info "APP_KEY generated"
    else
        log_info "APP_KEY already set"
    fi
}

# ═══════════════════════════════════════════════════════════════════════════
#  STEP 6 — Composer Install
# ═══════════════════════════════════════════════════════════════════════════

install_composer() {
    log_step "6/15 — Installing Composer dependencies"

    cd "$BACKEND_DIR"

    if command -v composer &>/dev/null; then
        composer install --no-interaction --prefer-dist --optimize-autoloader 2>&1 | tail -3
        log_info "Composer dependencies installed"
    elif command -v docker &>/dev/null; then
        log_info "Installing via Docker (composer image)..."
        docker run --rm \
            -v "$BACKEND_DIR:/app" \
            -v "${COMPOSER_HOME:-$HOME/.composer}:/tmp/cache" \
            composer:latest \
            install --no-interaction --prefer-dist --optimize-autoloader 2>&1 | tail -3
        log_info "Composer dependencies installed via Docker"
    else
        log_warn "Skipping Composer install — no PHP or Docker available"
    fi
}

# ═══════════════════════════════════════════════════════════════════════════
#  STEP 7 — NPM Install
# ═══════════════════════════════════════════════════════════════════════════

install_npm() {
    log_step "7/15 — Installing NPM dependencies"

    if [[ ! -f "$BACKEND_DIR/package.json" ]]; then
        log_info "No package.json found in backend — skipping"
        return
    fi

    if command -v npm &>/dev/null; then
        cd "$BACKEND_DIR"
        npm install 2>&1 | tail -3
        log_info "NPM dependencies installed"
    elif command -v docker &>/dev/null; then
        log_info "Installing via Docker (node image)..."
        docker run --rm \
            -v "$BACKEND_DIR:/app" \
            -w /app \
            node:20-alpine \
            npm install 2>&1 | tail -3
        log_info "NPM dependencies installed via Docker"
    else
        log_warn "Skipping NPM install — no Node or Docker available"
    fi
}

# ═══════════════════════════════════════════════════════════════════════════
#  STEP 8-9 — Database Migrations & Seeding
# ═══════════════════════════════════════════════════════════════════════════

run_migrations() {
    log_step "8/15 — Running database migrations"

    cd "$BACKEND_DIR"

    if [[ "${CI_MODE:-false}" == "true" ]]; then
        log_info "CI mode: running migrate:fresh"
        php artisan migrate:fresh --force --no-interaction 2>&1 | tail -5
    elif [[ "${RESET_MODE:-false}" == "true" ]]; then
        log_info "Reset mode: running migrate:fresh --seed"
        php artisan migrate:fresh --force --seed --no-interaction 2>&1 | tail -5
    else
        php artisan migrate --force --no-interaction 2>&1 | tail -5
    fi

    log_info "Migrations complete"
}

seed_database() {
    log_step "9/15 — Seeding database with test data"

    cd "$BACKEND_DIR"

    php artisan db:seed --force --no-interaction 2>&1 | tail -5

    log_info "Database seeded"
}

# ═══════════════════════════════════════════════════════════════════════════
#  STEP 10 — Redis Setup
# ═══════════════════════════════════════════════════════════════════════════

setup_redis() {
    log_step "10/15 — Setting up Redis"

    if command -v redis-cli &>/dev/null; then
        if redis-cli ping 2>/dev/null | grep -q PONG; then
            log_info "Redis is running locally"
        else
            log_warn "Redis not available locally — will be available via Docker"
        fi
    else
        log_warn "redis-cli not installed locally — will be available via Docker"
    fi

    # Update .env for Docker-based Redis
    sed -i 's|^REDIS_HOST=.*|REDIS_HOST=redis|' "$ENV_FILE"
    sed -i 's|^REDIS_PASSWORD=.*|REDIS_PASSWORD=null|' "$ENV_FILE"

    log_info "Redis configuration updated in .env"
}

# ═══════════════════════════════════════════════════════════════════════════
#  STEP 11 — Create Directories
# ═══════════════════════════════════════════════════════════════════════════

create_directories() {
    log_step "11/15 — Creating required directories"

    mkdir -p "$BACKEND_DIR/storage/framework/cache/data"
    mkdir -p "$BACKEND_DIR/storage/framework/sessions"
    mkdir -p "$BACKEND_DIR/storage/framework/views"
    mkdir -p "$BACKEND_DIR/storage/logs"
    mkdir -p "$BACKEND_DIR/storage/app/public"
    mkdir -p "$BACKEND_DIR/storage/app/uploads"
    mkdir -p "$BACKEND_DIR/storage/debugbar"
    mkdir -p "$BACKEND_DIR/bootstrap/cache"
    mkdir -p "$BACKEND_DIR/public/build"

    mkdir -p "$PROJECT_DIR/docker/nginx/ssl"
    mkdir -p "$PROJECT_DIR/docker/nginx/certbot/logs"
    mkdir -p "$PROJECT_DIR/docker/postgres/init"

    mkdir -p "$AI_GATEWAY_DIR/logs"
    mkdir -p "$AI_GATEWAY_DIR/tmp"

    mkdir -p "$FRONTEND_DIR/landing/dist"
    mkdir -p "$FRONTEND_DIR/console/dist"

    if [[ -d "$MONITORING_DIR" ]]; then
        mkdir -p "$MONITORING_DIR/grafana/data"
        mkdir -p "$MONITORING_DIR/prometheus/data"
        mkdir -p "$MONITORING_DIR/loki/data"
        mkdir -p "$MONITORING_DIR/tempo/data"
    fi

    log_info "All directories created"
}

# ═══════════════════════════════════════════════════════════════════════════
#  STEP 12 — Set Permissions
# ═══════════════════════════════════════════════════════════════════════════

set_permissions() {
    log_step "12/15 — Setting permissions"

    # Storage: writable by web server (www-data:33) and current user
    chmod -R 775 "$BACKEND_DIR/storage"
    chmod -R 775 "$BACKEND_DIR/bootstrap/cache"

    # Try to set proper ownership
    if [[ "$(uname -s)" == "Linux" ]]; then
        if command -v id &>/dev/null; then
            chown -R "$(id -u):$(id -g)" "$BACKEND_DIR/storage" 2>/dev/null || true
            chown -R "$(id -u):$(id -g)" "$BACKEND_DIR/bootstrap/cache" 2>/dev/null || true
        fi
        # Also allow www-data group for Docker
        chmod -R g+ws "$BACKEND_DIR/storage" 2>/dev/null || true
        chmod -R g+ws "$BACKEND_DIR/bootstrap/cache" 2>/dev/null || true
    fi

    # SSL certs
    chmod 600 "$PROJECT_DIR/docker/nginx/ssl/privkey.pem" 2>/dev/null || true
    chmod 644 "$PROJECT_DIR/docker/nginx/ssl/"*.pem 2>/dev/null || true

    # Scripts
    chmod +x "$PROJECT_DIR/scripts/"*.sh

    log_info "Permissions set"
}

# ═══════════════════════════════════════════════════════════════════════════
#  STEP 13-14 — Build Images & Start Services
# ═══════════════════════════════════════════════════════════════════════════

build_images() {
    log_step "13/15 — Building Docker images"

    log_info "Building core services..."
    $DOCKER_COMPOSE -f "$COMPOSE_FILE" build --pull --parallel 2>&1 | tail -5

    if [[ -f "$MONITORING_COMPOSE" ]]; then
        log_info "Building monitoring services..."
        $DOCKER_COMPOSE_MONITORING build --pull 2>&1 | tail -5
    fi

    log_info "Docker images built"
}

start_services() {
    log_step "14/15 — Starting services"

    log_info "Starting core services..."
    $DOCKER_COMPOSE -f "$COMPOSE_FILE" up -d --remove-orphans 2>&1 | tail -5

    if [[ -f "$MONITORING_COMPOSE" ]]; then
        log_info "Starting monitoring services..."
        $DOCKER_COMPOSE_MONITORING up -d --remove-orphans 2>&1 | tail -5
    fi

    log_info "Services started"
}

# ═══════════════════════════════════════════════════════════════════════════
#  STEP 15 — Health Check
# ═══════════════════════════════════════════════════════════════════════════

health_check() {
    log_step "15/15 — Checking service health"

    local all_healthy=true
    local max_retries=30
    local retry_interval=3

    echo ""
    printf "%-30s %s\n" "SERVICE" "STATUS"
    printf "%-30s %s\n" "-------" "------"

    check_service() {
        local name=$1
        local container=$2
        local url=$3
        local retries=${4:-$max_retries}

        for ((i = 0; i < retries; i++)); do
            local status
            status=$($DOCKER_COMPOSE -f "$COMPOSE_FILE" ps "$container" --format '{{.Status}}' 2>/dev/null || echo "")

            if echo "$status" | grep -qE "(healthy|running|up)"; then
                if [[ -n "$url" ]]; then
                    if curl -sf "$url" &>/dev/null; then
                        printf "%-30s ${GREEN}✓${RESET} healthy\n" "$name"
                        return 0
                    fi
                else
                    printf "%-30s ${GREEN}✓${RESET} running\n" "$name"
                    return 0
                fi
            fi
            sleep "$retry_interval"
        done

        printf "%-30s ${RED}✗${RESET} unhealthy\n" "$name"
        all_healthy=false
        return 1
    }

    check_service "PostgreSQL" "postgres" "" 15
    check_service "Redis" "redis" "redis-cli -h localhost ping" 10
    check_service "PHP-FPM" "php" "" 15
    check_service "AI Gateway" "ai-gateway" "http://localhost:8000/health" 15
    check_service "Nginx" "nginx" "http://localhost:80/health" 15
    check_service "Queue Worker" "queue" "" 10
    check_service "Scheduler" "scheduler" "" 10

    if [[ -f "$MONITORING_COMPOSE" ]]; then
        check_service "Prometheus" "prometheus" "http://localhost:9090/-/ready" 10 2>/dev/null || true
        check_service "Grafana" "grafana" "http://localhost:3000/api/health" 10 2>/dev/null || true
    fi

    echo ""

    if [[ "$all_healthy" == "true" ]]; then
        log_info "All services are healthy!"
    else
        log_warn "Some services are not healthy. Check logs with: $0 logs"
    fi
}

# ═══════════════════════════════════════════════════════════════════════════
#  DISPLAY — Service URLs & Credentials
# ═══════════════════════════════════════════════════════════════════════════

display_info() {
    log_banner "Corex.dev — Development Environment Ready"

    echo ""
    echo -e "  ${BOLD}Application URLs${RESET}"
    echo -e "  ─────────────────────────────────────────────────────────────"
    echo -e "  Landing Page:       ${CYAN}http://localhost:8080${RESET}"
    echo -e "  Console App:        ${CYAN}http://localhost:5173${RESET}"
    echo -e "  API Base:           ${CYAN}http://localhost:8080/api${RESET}"
    echo -e "  API Docs:           ${CYAN}http://localhost:8000/docs${RESET}"
    echo -e "  Health Check:       ${CYAN}http://localhost:8080/api/health${RESET}"
    echo ""

    echo -e "  ${BOLD}Infrastructure${RESET}"
    echo -e "  ─────────────────────────────────────────────────────────────"
    echo -e "  PostgreSQL:         ${CYAN}localhost:5432${RESET} (corex / corex:${DB_PASSWORD})"
    echo -e "  Redis:              ${CYAN}localhost:6379${RESET}"
    echo -e "  Mailpit:            ${CYAN}http://localhost:8025${RESET}"
    echo ""

    if [[ -f "$MONITORING_COMPOSE" ]]; then
        echo -e "  ${BOLD}Monitoring${RESET}"
        echo -e "  ─────────────────────────────────────────────────────────────"
        echo -e "  Grafana:            ${CYAN}http://localhost:3000${RESET} (admin / admin)"
        echo -e "  Prometheus:         ${CYAN}http://localhost:9090${RESET}"
        echo -e "  Loki:               ${CYAN}http://localhost:3100${RESET}"
        echo -e "  Tempo:              ${CYAN}http://localhost:4318${RESET}"
        echo -e "  Alertmanager:       ${CYAN}http://localhost:9093${RESET}"
        echo ""
    fi

    echo -e "  ${BOLD}Test Credentials${RESET}"
    echo -e "  ─────────────────────────────────────────────────────────────"
    echo -e "  Admin:              ${YELLOW}admin@corex.dev${RESET} / ${YELLOW}password${RESET}"
    echo -e "  User:               ${YELLOW}user@corex.dev${RESET}  / ${YELLOW}password${RESET}"
    echo ""

    echo -e "  ${BOLD}Helper Commands${RESET}"
    echo -e "  ─────────────────────────────────────────────────────────────"
    echo -e "  ${MAGENTA}source scripts/init-dev.sh${RESET}   Load helper functions"
    echo -e "  ${MAGENTA}start-dev${RESET}                    Start all services"
    echo -e "  ${MAGENTA}stop-dev${RESET}                     Stop all services"
    echo -e "  ${MAGENTA}logs${RESET}                         Tail combined logs"
    echo -e "  ${MAGENTA}test${RESET}                         Run all tests"
    echo -e "  ${MAGENTA}clean${RESET}                        Remove volumes and caches"
    echo ""
}

# ═══════════════════════════════════════════════════════════════════════════
#  HELPER FUNCTIONS (for sourcing)
# ═══════════════════════════════════════════════════════════════════════════

start-dev() {
    echo -e "${CYAN}Starting Corex.dev services...${RESET}"
    $DOCKER_COMPOSE -f "$COMPOSE_FILE" up -d --remove-orphans
    if [[ -f "$MONITORING_COMPOSE" ]]; then
        $DOCKER_COMPOSE_MONITORING up -d --remove-orphans
    fi
    health_check
}

stop-dev() {
    echo -e "${YELLOW}Stopping Corex.dev services...${RESET}"
    $DOCKER_COMPOSE -f "$COMPOSE_FILE" down --remove-orphans
    if [[ -f "$MONITORING_COMPOSE" ]]; then
        $DOCKER_COMPOSE_MONITORING down --remove-orphans
    fi
    echo -e "${GREEN}All services stopped${RESET}"
}

logs() {
    local follow="${1:--f}"
    local services=("nginx" "php" "ai-gateway" "postgres" "redis" "queue")

    echo -e "${CYAN}Tailing logs for core services...${RESET}"
    $DOCKER_COMPOSE -f "$COMPOSE_FILE" logs "$follow" "${services[@]}"
}

test() {
    echo -e "${BOLD}${CYAN}══════ Running Corex.dev Test Suite ══════${RESET}\n"

    local exit_code=0

    # PHP tests
    if [[ -f "$BACKEND_DIR/phpunit.xml" ]] || [[ -f "$BACKEND_DIR/phpunit.xml.dist" ]]; then
        echo -e "${BOLD}PHPUnit Tests${RESET}"
        cd "$BACKEND_DIR"
        if php artisan test --compact --no-interaction 2>/dev/null; then
            echo -e "${GREEN}✓ PHP tests passed${RESET}\n"
        else
            echo -e "${RED}✗ PHP tests failed${RESET}\n"
            exit_code=1
        fi
    fi

    # Python tests
    if [[ -f "$AI_GATEWAY_DIR/pytest.ini" ]] || [[ -f "$AI_GATEWAY_DIR/pyproject.toml" ]]; then
        echo -e "${BOLD}Pytest Suite${RESET}"
        cd "$AI_GATEWAY_DIR"
        if python -m pytest --asyncio-mode=auto -v --tb=short 2>/dev/null; then
            echo -e "${GREEN}✓ Python tests passed${RESET}\n"
        else
            echo -e "${RED}✗ Python tests failed${RESET}\n"
            exit_code=1
        fi
    fi

    # Cypress E2E tests
    if [[ -f "$FRONTEND_DIR/cypress.config.js" ]] && command -v npx &>/dev/null; then
        echo -e "${BOLD}Cypress E2E Tests${RESET}"
        cd "$FRONTEND_DIR"
        if npx cypress run --e2e 2>/dev/null; then
            echo -e "${GREEN}✓ E2E tests passed${RESET}\n"
        else
            echo -e "${RED}✗ E2E tests failed${RESET}\n"
            exit_code=1
        fi
    fi

    # k6 smoke test
    if command -v k6 &>/dev/null; then
        echo -e "${BOLD}k6 Smoke Test${RESET}"
        if k6 run "$PROJECT_DIR/k6/scripts/smoke.js" 2>/dev/null; then
            echo -e "${GREEN}✓ k6 smoke test passed${RESET}\n"
        else
            echo -e "${YELLOW}⚠ k6 smoke test completed with issues${RESET}\n"
        fi
    fi

    echo -e "${BOLD}${CYAN}══════ Test suite complete ══════${RESET}"
    return $exit_code
}

clean() {
    echo -e "${RED}Cleaning Corex.dev development environment...${RESET}\n"

    # Confirm unless --force
    if [[ "${1:-}" != "--force" ]]; then
        echo -e "${YELLOW}This will remove ALL Docker volumes, caches, and build artifacts.${RESET}"
        echo -n "Are you sure? [y/N] "
        read -r confirm
        if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
            echo "Cancelled"
            return 1
        fi
    fi

    # Stop and remove containers + volumes
    echo "Stopping services..."
    $DOCKER_COMPOSE -f "$COMPOSE_FILE" down -v --remove-orphans 2>/dev/null || true
    if [[ -f "$MONITORING_COMPOSE" ]]; then
        $DOCKER_COMPOSE_MONITORING down -v --remove-orphans 2>/dev/null || true
    fi

    # Remove caches and build artifacts
    echo "Removing caches..."
    rm -rf "$BACKEND_DIR/storage/framework/cache"/*
    rm -rf "$BACKEND_DIR/storage/framework/views"/*
    rm -rf "$BACKEND_DIR/storage/framework/sessions"/*
    rm -rf "$BACKEND_DIR/storage/logs"/*
    rm -rf "$BACKEND_DIR/bootstrap/cache"/*
    rm -rf "$BACKEND_DIR/vendor" 2>/dev/null || true
    rm -rf "$BACKEND_DIR/node_modules" 2>/dev/null || true
    rm -rf "$BACKEND_DIR/public/build"/* 2>/dev/null || true
    rm -rf "$AI_GATEWAY_DIR/.venv" 2>/dev/null || true
    rm -rf "$AI_GATEWAY_DIR/__pycache__" 2>/dev/null || true
    rm -rf "$AI_GATEWAY_DIR/**/__pycache__" 2>/dev/null || true

    # Monitoring data
    if [[ -d "$MONITORING_DIR" ]]; then
        rm -rf "$MONITORING_DIR/grafana/data"/* 2>/dev/null || true
        rm -rf "$MONITORING_DIR/prometheus/data"/* 2>/dev/null || true
        rm -rf "$MONITORING_DIR/loki/data"/* 2>/dev/null || true
        rm -rf "$MONITORING_DIR/tempo/data"/* 2>/dev/null || true
    fi

    # SSL certs (recreate on next init)
    rm -f "$PROJECT_DIR/docker/nginx/ssl/"*.pem 2>/dev/null || true

    # Remove Docker images (optional)
    echo ""
    echo -e "${YELLOW}Remove built Docker images too?${RESET}"
    echo -n "This requires rebuilding. [y/N] "
    read -r confirm_images
    if [[ "$confirm_images" == "y" || "$confirm_images" == "Y" ]]; then
        $DOCKER_COMPOSE -f "$COMPOSE_FILE" down --rmi all 2>/dev/null || true
    fi

    echo ""
    echo -e "${GREEN}Clean complete. Run './scripts/init-dev.sh' to start fresh.${RESET}"
}

export -f start-dev stop-dev logs test clean

# ═══════════════════════════════════════════════════════════════════════════
#  MAIN
# ═══════════════════════════════════════════════════════════════════════════

main() {
    log_banner "Corex.dev — Development Environment Setup"

    CI_MODE=false
    RESET_MODE=false
    QUICK_MODE=false

    for arg in "$@"; do
        case "$arg" in
            --ci)   CI_MODE=true ;;
            --reset) RESET_MODE=true ;;
            --quick) QUICK_MODE=true ;;
            --help|-h)
                echo "Usage: $0 [OPTIONS]"
                echo ""
                echo "Options:"
                echo "  --quick   Skip image builds and seeds, just start services"
                echo "  --reset   Destroy all volumes and start fresh"
                echo "  --ci      Non-interactive CI mode (no sudo, migrate:fresh)"
                echo "  --help    Show this help"
                echo ""
                echo "Source this script to use helper functions:"
                echo "  source $0"
                echo "  start-dev  |  stop-dev  |  logs  |  test  |  clean"
                exit 0
                ;;
        esac
    done

    if [[ "$QUICK_MODE" == "true" ]]; then
        log_warn "Quick mode: skipping builds, seeds, and full checks"
        start_services
        health_check
        display_info
        exit 0
    fi

    check_docker
    check_docker_compose
    create_env_file
    generate_ssl_certs
    generate_laravel_key

    if [[ "$CI_MODE" == "false" ]]; then
        install_composer
        install_npm
    else
        log_info "CI mode: skipping dependency installation"
    fi

    setup_redis
    create_directories
    set_permissions

    if [[ "$RESET_MODE" == "true" ]]; then
        log_warn "Reset mode: destroying existing volumes"
        $DOCKER_COMPOSE -f "$COMPOSE_FILE" down -v --remove-orphans 2>/dev/null || true
    fi

    build_images
    start_services
    run_migrations
    seed_database
    health_check
    display_info
}

# ── Detect if being sourced or executed ───────────────────────────────────
if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
    echo -e "${GREEN}Corex.dev helper functions loaded.${RESET}"
    echo -e "  ${MAGENTA}start-dev${RESET}  ${MAGENTA}stop-dev${RESET}  ${MAGENTA}logs${RESET}  ${MAGENTA}test${RESET}  ${MAGENTA}clean${RESET}"
    echo ""
else
    main "$@"
fi
